integrations:
  app_store_connect:
    integration_name: NK_Tomislav

workflows:
  ios-build:
    name: iOS Build for TestFlight
    environment:
      vars:
        BUNDLE_ID: "com.example.tomislav"
        FLUTTER_BUILD_MODE: release
        FLUTTER_IOS_DEPLOYMENT_TARGET: 13.0
      groups:
        - app_store_credentials
        - firebase_credentials
      flutter: stable
      xcode: latest

    caching:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ios/.symlinks

    scripts:
      - name: Set up Firebase
        script: |
          mkdir -p ios/Runner
          echo $GOOGLE_SERVICE_INFO | base64 --decode > ios/Runner/GoogleService-Info.plist
          plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Install pods
        script: |
          cd ios
          pod repo update
          pod install --repo-update

      - name: Build IPA
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
          ls -la build/ios/ipa/  # Verify IPA exists

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_build.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true