integrations:
  app_store_connect:
    integration_name: NK_Tomislav

workflows:
  ios-build:
    name: iOS Build for TestFlight
    environment:
      vars:
        BUNDLE_ID: "com.example.tomislav"
      groups:
        - app_store_credentials
      flutter: stable
      xcode: latest

    scripts:
      - name: Decode GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Flutter clean & build
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: NK_Tomislav
        submit_to_testflight: true

    # Tell Codemagic to use the uploaded provisioning profile and certificate
    # (these will be automatically matched by Codemagic by bundle ID and cert name)
    code_signing:
      ios:
        distribution_certificate: NK_Tomislav Distribution Certificate
        provisioning_profile: NK_Tomislav App Store Profile
