workflows:
  ios-build:
    name: iOS Build for TestFlight
    environment:
      vars:
        BUNDLE_ID: "com.example.tomislav"
      groups:
        - app_store_credentials
        - firebase_credentials
      flutter: stable
      xcode: latest
      ios:
        automatic_code_signing:
          enabled: true
          apple_team_id: 5S96S5CF9V
    scripts:
      - name: Decode GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Decode App Store Connect API key
        script: |
          echo $APP_STORE_CONNECT_API_KEY > authkey.p8

      - name: Flutter clean & build
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth:
          api_key: authkey.p8
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key_id: $APP_STORE_CONNECT_KEY_ID
        submit_to_testflight: true
