integrations:
  app_store_connect:
    integration_name: NK_Tomislav

workflows:
  ios-build:
    name: iOS Build for TestFlight
    environment:
      vars:
        BUNDLE_ID: "com.example.tomislav"
        FLUTTER_BUILD_MODE: release
        FLUTTER_IOS_DEPLOYMENT_TARGET: 13.0
      groups:
        - app_store_credentials
        - firebase_credentials  # Contains your GOOGLE_SERVICE_INFO
      flutter: stable
      xcode: latest

    scripts:
      - name: Setup Firebase
        script: |
          # Create directory and decode Firebase config
          mkdir -p ios/Runner
          echo $GOOGLE_SERVICE_INFO | base64 --decode > ios/Runner/GoogleService-Info.plist
          
          # Force iOS 13.0 deployment target
          plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true