name: tomislav
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  icons_plus: ^5.0.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  cloud_firestore: ^5.6.6
  url_launcher: ^6.3.1
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#1565C0"
  image: assets/images/slika.jpg
  branding: assets/images/slika.jpg
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/NK_Tomislav.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/NK_Tomislav.png
    - assets/images/slika.jpg
